#!/usr/bin/env python
"""Weekly monitoring orchestration - two independent checks, both writing JSON (+ HTML for
data drift) reports under outputs/monitoring/, readable via the API's GET /monitoring/status:

1. Prediction/calibration drift for the week that JUST completed: grades the predictions
   already generated for that week (by the API's GET /predictions/week or
   scripts/generate_weekly_predictions.py) against now-known realized outcomes, and appends
   to the rolling precision log.
2. Data drift for the UPCOMING week: compares its incoming (post-feature-engineering,
   pre-selection) feature frame against the artifact's training-time reference snapshot.

These are independent because a "completed" week has outcomes but its predictions may have
been generated by an older artifact version (hence --artifact-version defaults to reading the
predictions CSV's own recorded version, not whatever happens to be `latest` right now), while
an "upcoming" week has no outcomes yet at all.

Usage:
    python scripts/run_weekly_monitoring.py \\
        --completed-season 2026 --completed-week 3 \\
        --upcoming-season 2026 --upcoming-week 4
    python scripts/run_weekly_monitoring.py --completed-season 2026 --completed-week 3
        (prediction-drift check only, skips the upcoming-week data-drift check)
    python scripts/run_weekly_monitoring.py --upcoming-season 2026 --upcoming-week 4 --live
        (data-drift check only, pulling the upcoming week live from the CFBD API)
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

import pandas as pd

from cfb_cover_model.config import load_data_config
from cfb_cover_model.monitoring.data_drift import run_data_drift_report
from cfb_cover_model.monitoring.prediction_drift import evaluate_completed_week
from cfb_cover_model.serving.artifact import (
    DATASET_PATH,
    EXTENDED_HISTORY_PATH,
    PRODUCTION_DIR,
    load_artifact,
    load_latest_artifact,
)
from cfb_cover_model.serving.scoring import build_feature_frame

PREDICTIONS_DIR = Path(__file__).resolve().parents[1] / "outputs" / "predictions"


def _default_predictions_path(season: int, week: int) -> Path:
    candidates = [
        PREDICTIONS_DIR / f"week_{week}_dual_model_predictions.csv",
        PREDICTIONS_DIR / f"live_{season}_week_{week}_dual_model_predictions.csv",
    ]
    for c in candidates:
        if c.exists():
            return c
    raise FileNotFoundError(
        f"No predictions file found for season={season} week={week} - tried {candidates}. "
        "Pass --predictions-file explicitly, or generate predictions for this week first."
    )


def _load_realized_outcomes(season: int, week: int) -> pd.DataFrame:
    frames = []
    if Path(DATASET_PATH).exists():
        frames.append(pd.read_parquet(DATASET_PATH))
    if Path(EXTENDED_HISTORY_PATH).exists():
        frames.append(pd.read_parquet(EXTENDED_HISTORY_PATH))
    if not frames:
        raise FileNotFoundError("Neither modeling_dataset.parquet nor extended_history.parquet exists yet.")
    history = pd.concat(frames, ignore_index=True)
    outcomes = history[(history["season"] == season) & (history["week"] == week)]
    if outcomes.empty:
        raise ValueError(
            f"No realized outcomes found for season={season} week={week} - has "
            "scripts/ingest_and_update_history.py been run for this week yet?"
        )
    return outcomes[["game_id", "home_covered"]].drop_duplicates("game_id")


def run_prediction_drift_check(completed_season: int, completed_week: int, predictions_file: str | None, artifact_version: str | None) -> dict:
    predictions_path = Path(predictions_file) if predictions_file else _default_predictions_path(completed_season, completed_week)
    predictions_df = pd.read_csv(predictions_path)

    version = artifact_version or (
        predictions_df["artifact_version"].iloc[0] if "artifact_version" in predictions_df.columns else None
    )
    if version:
        artifact = load_artifact(PRODUCTION_DIR / version)
    else:
        artifact = load_latest_artifact()
        if artifact is None:
            raise RuntimeError("No artifact_version recorded in predictions file and no latest artifact exists.")

    outcomes = _load_realized_outcomes(completed_season, completed_week)
    summary = evaluate_completed_week(
        predictions_df, outcomes, artifact.classifier_threshold, artifact.regressor_threshold,
        season=completed_season, week=completed_week,
    )
    print(f"[prediction-drift] season={completed_season} week={completed_week}: {summary}")
    return summary


def run_data_drift_check(upcoming_season: int, upcoming_week: int, live: bool) -> dict:
    artifact = load_latest_artifact()
    if artifact is None:
        raise RuntimeError("No production artifact exists yet - run scripts/train_production_artifact.py first.")

    data_cfg = load_data_config()
    if live:
        from cfb_cover_model.ingest import cfbd_client, pipeline

        client = cfbd_client.get_client()
        week_df_raw = pipeline.build_current_week_rows(client, upcoming_season, upcoming_week)
    else:
        from cfb_cover_model.data import load_week_predictors_df
        from cfb_cover_model.config import resolve_path

        path = resolve_path(data_cfg["paths"]["predictors_csv"]).parent / f"CFB_Pred_Week_{upcoming_week}.csv"
        if not path.exists():
            raise FileNotFoundError(f"Upcoming week file not found: {path}. Pass --live to pull from the CFBD API instead.")
        week_df_raw = load_week_predictors_df(path)

    _, week_variant, week_cols = build_feature_frame(
        week_df_raw, artifact.feature_columns, artifact.transforms, artifact.representation, data_cfg
    )
    common_cols = [c for c in artifact.selected_columns if c in week_cols]

    label = f"{upcoming_season}_week_{upcoming_week}"
    summary = run_data_drift_report(
        artifact.reference_training_frame, week_variant[week_cols], common_cols, label=label
    )
    print(f"[data-drift] season={upcoming_season} week={upcoming_week}: {summary}")
    return summary


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--completed-season", type=int, default=None)
    parser.add_argument("--completed-week", type=int, default=None)
    parser.add_argument("--upcoming-season", type=int, default=None)
    parser.add_argument("--upcoming-week", type=int, default=None)
    parser.add_argument("--predictions-file", type=str, default=None)
    parser.add_argument("--artifact-version", type=str, default=None)
    parser.add_argument("--live", action="store_true", help="Pull the upcoming week's raw frame from the CFBD API")
    args = parser.parse_args()

    if args.completed_season is None and args.upcoming_season is None:
        parser.error("Pass at least one of --completed-season/--completed-week or --upcoming-season/--upcoming-week")

    exit_code = 0

    if args.completed_season is not None:
        if args.completed_week is None:
            parser.error("--completed-season requires --completed-week")
        try:
            run_prediction_drift_check(args.completed_season, args.completed_week, args.predictions_file, args.artifact_version)
        except Exception as e:
            print(f"[prediction-drift] FAILED: {e}", file=sys.stderr)
            exit_code = 1

    if args.upcoming_season is not None:
        if args.upcoming_week is None:
            parser.error("--upcoming-season requires --upcoming-week")
        try:
            run_data_drift_check(args.upcoming_season, args.upcoming_week, args.live)
        except Exception as e:
            print(f"[data-drift] FAILED: {e}", file=sys.stderr)
            exit_code = 1

    sys.exit(exit_code)


if __name__ == "__main__":
    main()
