#!/usr/bin/env python
"""Step 1 of the pipeline. Inspects the raw MySQL cache and writes a data inventory to
outputs/data_inventory/. Standalone-runnable, no dependency on features/ or modeling/.

Usage:
    python scripts/inspect_database.py
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from cfb_win_total_model import data_validation as dv
from cfb_win_total_model.database import get_engine
from cfb_win_total_model.utils.logging import get_logger
from cfb_win_total_model.utils.paths import OUTPUTS_DATA_INVENTORY, ensure_dirs

logger = get_logger(__name__)


def main() -> int:
    ensure_dirs()
    engine = get_engine()

    logger.info("Running database inspection checks...")
    results = dv.run_all_checks(engine)

    summary_lines = ["# Data Inventory Summary", "", "Auto-generated by scripts/inspect_database.py.", ""]
    hard_fail = False

    row_counts = results["row_counts"]
    row_counts.to_csv(OUTPUTS_DATA_INVENTORY / "row_counts.csv", index=False)
    summary_lines.append("## Row counts")
    summary_lines.append(row_counts.to_markdown(index=False))
    summary_lines.append("")

    season_ranges = results["season_ranges"]
    season_ranges.to_csv(OUTPUTS_DATA_INVENTORY / "season_ranges.csv", index=False)
    summary_lines.append("## Season ranges")
    summary_lines.append(season_ranges.to_markdown(index=False))
    summary_lines.append("")

    summary_lines.append("## Duplicate-key checks (hard-fail if any non-empty)")
    for table, dupes in results["duplicate_keys"].items():
        status = "FAIL" if not dupes.empty else "PASS"
        if not dupes.empty:
            hard_fail = True
            dupes.to_csv(OUTPUTS_DATA_INVENTORY / f"duplicate_keys_{table}.csv", index=False)
        summary_lines.append(f"- `{table}`: {status} ({len(dupes)} duplicate key groups)")
    summary_lines.append("")

    fbs_counts = results["fbs_team_counts_by_season"]
    fbs_counts.to_csv(OUTPUTS_DATA_INVENTORY / "fbs_team_counts_by_season.csv", index=False)
    summary_lines.append("## FBS team counts by season")
    summary_lines.append(fbs_counts.to_markdown(index=False))
    summary_lines.append("")

    coverage = results["game_team_stats_coverage"]
    coverage.to_csv(OUTPUTS_DATA_INVENTORY / "game_team_stats_coverage.csv", index=False)
    min_coverage = coverage["match_rate"].min()
    summary_lines.append(f"## game_team_stats coverage (min match rate: {min_coverage:.4f})")
    summary_lines.append(coverage.to_markdown(index=False))
    summary_lines.append("")

    covid = results["covid_season_flag"]
    covid.to_csv(OUTPUTS_DATA_INVENTORY / "covid_season_flag.csv", index=False)
    summary_lines.append("## Shortened-season flag (games/plays count by season)")
    summary_lines.append(covid.to_markdown(index=False))
    summary_lines.append("")

    roster_year = results["roster_year_reliability"]
    roster_year.to_csv(OUTPUTS_DATA_INVENTORY / "roster_year_reliability.csv", index=False)
    leaked_rows = int(roster_year.loc[roster_year["season_leaked_into_year"], "n"].sum())
    total_rows = int(roster_year["n"].sum())
    summary_lines.append(
        f"## team_rosters.year reliability: {leaked_rows}/{total_rows} rows "
        f"({leaked_rows/total_rows:.2%}) have season leaked into the class-year field"
    )
    summary_lines.append("")

    for key in (
        "missingness_team_rosters_year",
        "missingness_coaches_preseason_rank",
        "missingness_returning_production",
    ):
        df = results[key]
        df.to_csv(OUTPUTS_DATA_INVENTORY / f"{key}.csv", index=False)

    summary_lines.append("## Missingness reports")
    summary_lines.append("See `missingness_*.csv` for per-season, per-column null rates.")
    summary_lines.append("")

    overall_status = "FAIL" if hard_fail else "PASS"
    summary_lines.insert(2, f"**Overall status: {overall_status}**")

    (OUTPUTS_DATA_INVENTORY / "inspection_summary.md").write_text("\n".join(summary_lines))
    logger.info(f"Data inventory written to {OUTPUTS_DATA_INVENTORY}")

    if hard_fail:
        logger.error("Inspection found duplicate-key integrity violations -- see inspection_summary.md")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
