#!/usr/bin/env python
"""Step 1 of the pipeline. Inspects the raw MySQL cache and writes a data inventory to
outputs/data_inventory/. Standalone-runnable, no dependency on features/ or modeling/.

Usage:
    python scripts/inspect_database.py
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from cfb_rb_rushing_model import data_validation as dv
from cfb_rb_rushing_model.config import load_data_config
from cfb_rb_rushing_model.database import get_engine
from cfb_rb_rushing_model.utils.logging import get_logger
from cfb_rb_rushing_model.utils.paths import OUTPUTS_DATA_INVENTORY, ensure_dirs

logger = get_logger(__name__)


def main() -> int:
    ensure_dirs()
    engine = get_engine()
    data_cfg = load_data_config()

    logger.info("Running database inspection checks...")
    results = dv.run_all_checks(engine, data_cfg.positions, data_cfg.name_suffixes_to_strip)

    summary_lines = ["# Data Inventory Summary", "", "Auto-generated by scripts/inspect_database.py.", ""]
    hard_fail = False

    row_counts = results["row_counts"]
    row_counts.to_csv(OUTPUTS_DATA_INVENTORY / "row_counts.csv", index=False)
    summary_lines.append("## Row counts")
    summary_lines.append(row_counts.to_markdown(index=False))
    summary_lines.append("")

    summary_lines.append("## Duplicate-key checks (hard-fail if any non-empty)")
    for table, dupes in results["duplicate_keys"].items():
        status = "FAIL" if not dupes.empty else "PASS"
        if not dupes.empty:
            hard_fail = True
            dupes.to_csv(OUTPUTS_DATA_INVENTORY / f"duplicate_keys_{table}.csv", index=False)
        summary_lines.append(f"- `{table}`: {status} ({len(dupes)} duplicate key groups)")
    summary_lines.append("")

    completeness = results["rusher_name_completeness"]
    completeness.to_csv(OUTPUTS_DATA_INVENTORY / "rusher_name_completeness_by_season.csv", index=False)
    n_fail_seasons = int((completeness["status"] == "FAIL").sum())
    summary_lines.append(f"## plays.rusher_player_name completeness by season ({n_fail_seasons} season(s) FAIL the {dv.MAX_ACCEPTABLE_RUSHER_NAME_NULL_RATE:.0%} NULL-rate floor)")
    summary_lines.append(completeness.to_markdown(index=False))
    summary_lines.append("")

    covid = results["covid_season_flag"]
    covid.to_csv(OUTPUTS_DATA_INVENTORY / "covid_season_flag.csv", index=False)
    summary_lines.append("## Shortened-season flag (games/plays count by season)")
    summary_lines.append(covid.to_markdown(index=False))
    summary_lines.append("")

    match_rates = results["player_resolution_match_rates"]
    match_rates.to_csv(OUTPUTS_DATA_INVENTORY / "player_resolution_match_rates.csv", index=False)
    n_warn = int((match_rates["status"] == "WARN").sum())
    summary_lines.append(f"## Player name-resolution match rates ({n_warn} season(s) WARN on any_position_unmatched_rate)")
    summary_lines.append(match_rates.to_markdown(index=False))
    summary_lines.append("")

    overall_status = "FAIL" if hard_fail else "PASS"
    summary_lines.insert(2, f"**Overall status: {overall_status}**")

    (OUTPUTS_DATA_INVENTORY / "inspection_summary.md").write_text("\n".join(summary_lines))
    logger.info(f"Data inventory written to {OUTPUTS_DATA_INVENTORY}")

    if hard_fail:
        logger.error("Inspection found duplicate-key integrity violations -- see inspection_summary.md")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
